### PR TITLE
Fix dead image reference to "Fork me on GitHub"

### PR DESCRIPTION
**Pull request by metalefty**
Switched to CSS implementation hosted on cdsjs.com. It should be more permanent than githubusercontent.com.

Resolves: #153

----

image

### CODE REVIEW

**Comment by geek-at** [comment]
Nice thank you! But I think you missed the actual css class of `github-fork-ribbon`

**Comment by metalefty** [comment]
Thanks, let me chck.

**Comment by geek-at** [comment]
Oh I see you included the css from a CDN. Can you please include it locally just to be more GDPR compliant 😁

**Comment by metalefty** [comment]
Understood, will do.

**Comment by metalefty** [comment]
Moved CSS to local.

**Comment by geek-at** [comment]
thank you 😁

**Pull request merged**
