### PR TITLE
Add SVG logo

### PR DESCRIPTION
**Pull request by gabe565**
This PR adds an SVG version of the logo to `css/imgs/logo/logo.svg` and uses it in `README.md`. I saw the existing `pictshare.ai` file, but opted to trace the image so I could keep it as close as possible to the existing PNG.

### CODE REVIEW

**Review by geek-at — CHANGES_REQUESTED** [review]
please link the pictshare logo to an absolute URL, not a relative one because that might break a coming feature

otherwise great work thank you 😁

**Comment by gabe565** [comment]
@geek-at thank you! I only intended for this to be in the repo's `README.md`, so relative makes it show the correct icon on forks or locally. You would want that to be an absolute URL to this repo?

**Comment by geek-at** [comment]
oh you're right, I misread and thought it was linked from the template. Thanks

**Comment by gabe565** [comment]
I'd like to swap that one to an SVG also! I'll open a PR to do that soon. Thanks for merging 🙂

**Pull request merged**
